"""Checkpoint loading helpers for optional torch models."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Union


def load_torch_checkpoint(path: Union[str, Path], map_location: Any = "cpu") -> Any:
    """Load a trusted OptiDiag checkpoint while avoiding torch.load warnings.

    PyTorch warns that the default `weights_only=False` can be unsafe for
    untrusted pickle files. OptiDiag checkpoints are produced by
    `scripts/train.py`; we first try the safer `weights_only=True` path and
    only fall back for older PyTorch versions or incompatible legacy files.
    """
    import torch

    try:
        return torch.load(path, map_location=map_location, weights_only=True)
    except TypeError:
        return torch.load(path, map_location=map_location)
    except Exception:
        # Fallback is only for trusted local training artifacts generated by
        # this project. Do not use this path for arbitrary downloaded files.
        return torch.load(path, map_location=map_location, weights_only=False)

